### ISSUE TITLE
Game crashes when holding shield in offhand

### ISSUE THREAD

**Issue by Josua-P** [DasHomi/preventer#13]
Every time you hold a shield in your offhand on a server, the game crashes.

Installed Mods: Preventer 0.8.5; Cloth Config 9.0.94; Fabric API 0.72.0
The default config is used.
Java Version: JDK 17.0.1
OS: Windows 10 Pro, Build 19045.2364
Crash log is attached.
[crash-2023-01-08_09.40.14-client.txt](https://github.com/DasHomi/preventer/files/10368091/crash-2023-01-08_09.40.14-client.txt)

**Comment by DasHomi** [comment]
Hi, I found the error, and it fixed it (hopefully). I will release Preventer 0.8.6 in a few minutes, which should contain the fix.

**Comment by DasHomi** [comment]
Ok, the new version should now be on modrinth & curseforge
