### ISSUE TITLE
[FEATURE] Prevent attacking friends

### ISSUE THREAD

**Issue by adabugra** [DasHomi/preventer#16]
A feature that prevents you from hitting your friends and also shooting them with arrows. A command like friend add can be added for adding friends

**Comment by DasHomi** [comment]
I'll think about it, but the part where you are prevented from shooting friends with arrows is nearly impossible to do client side (but this mod is client side only).

**Comment by DasHomi** [comment]
Ok so i don't think there is a good way to implement that with preventer. Though I'm currently working on another mod simular to Preventer in which this feature, at last the part where you block hitting Friends, fits quite well. So i'll try to put that in the other mod, but i don't yet know when that will happen.
