### ISSUE TITLE
[Feature] More mob options for attack prevention

### ISSUE THREAD

**Issue by BlueJayofEvil** [DasHomi/preventer#18]
If it's not too much trouble, I would like to request the following mobs as options for attack prevention:

-Iron Golems (goes hand-in-hand with preventing aggro around villagers and their protectors; could either be a separate option or a sub-option under the villager option)
-Snow Golems (lesser request following the iron golems)
-Allays (both wild and item holding ones)
-Wolves/dogs (don't want to aggro wild ones and don't want to hurt your pets by accident)
-Cats (similar reason as wolves)
-Parrots (wild and tamed; birds can't be bred and they're rather fragile HP-wise)
-Sniffers (I'd like to protect our newest gentle mob friends)
-Horses(/Donkeys/Mules) (including skeleton and zombie; the latter because they're a rare event and the latter in case of servers enabling them via other mods)
-Camels (similar reasons as horses)
-Bees (similar reason as wolves)
-Named and/or tamed mobs (this should cover anything not specified while being within reason)

Maybe possibly also add options to allow attacking mobs that are aggro (e.g. bees/wolves/zombie piglins) while keeping prevention of attacking peaceful ones enabled?

Thank you!

**Comment by DasHomi** [comment]
Sure, sounds good. I'll try to implement all or most of them until the 1.0 version. But I'm not quite sure yet if I'll do it as individual modules for each mob type, or one module with a list, or something like that.

**Comment by BlueJayofEvil** [comment]
Thank you for considering my suggestions!
But I realize I forgot to mention llamas (hate accidentally hitting a trader's llamas and getting spat on) and axolotls (which are friends worth protecting).
Again, thank you for this great mod!

**Comment by DasHomi** [comment]
Sure, I think i'll bundel "Horses" (Lamas, Horses, Donkeys, Mules, Camels, ...) Together and "Fragile rare mobs"(Axolotls, Bees, Parrots, ...) but this is not final yet.

**Comment by DasHomi** [comment]
Oh, and also, just to give you an update: The golems, Named and Tamed prevention options are already implemented. And the thing for agro mobs, i'll do as an optional "overried" that makes it always possible to attack angry mobs.

**Comment by BlueJayofEvil** [comment]
Sounds great!

**Comment by DasHomi** [comment]
So, I think I've basically implemented all your ideas in some form or shape. Only the Angry Mob Override is not yet implemented, as I've hit some unforeseen difficulties with detecting angry mobs client-side, but I'll try to get that done until the 1.0 release.

**Comment by DasHomi** [comment]
So, I've tried, but an "Agro override" is sadly simply not possible (to my knowledge) with a client-side mod as there is no way to get the necessary data client-side.
