### ISSUE TITLE
[Feature] Prevent suspicious sand and gravel breaking

### ISSUE THREAD

**Issue by CodingPanda0623** [DasHomi/preventer#19]
Hi! With the introduction of 1.20 I've noticed that I tend to accidentally break suspicious blocks at archaeology sites (especially at trail ruins) because I have an instamining shovel. If it's not too much trouble, I'd like to request a feature to prevent us from accidentally mining these suspicious blocks and if possible, maybe prevent us from mining blocks under it too so that they won't break by gravity. Thanks!

**Comment by DasHomi** [comment]
So, it's implemented and the option to prevent breaking of blocks above which there is a suspicious block is also implemented as a configuration option of the "prevent suspicious  block breaking" option.
