### ISSUE TITLE
[Feature] Prevent dropping named items from inventory

### ISSUE THREAD

**Issue by BlueJayofEvil** [DasHomi/preventer#20]
Inspired by the hotbar tool drop prevention and an incident that happened on a server recently, would it be possible to prevent dropping of named items from your inventory?
Nothing brings you down like having your precious custom-named shulker box get dropped by accident and burn up in lava along with its contents.
I figure anything you would want to keep protected like that would be easy enough to add a custom name, so this would apply to anything players would want to prevent accidental dropping, tools or otherwise.
Thanks again!

**Comment by DasHomi** [comment]
yeah sounds possible and like a good idea so i'll implement that
