### ISSUE TITLE
Prevent breaking sugar cane from bottom

### ISSUE THREAD

**Issue by Lerkista** [DasHomi/preventer#25]
Can you implement an option to prevent breaking a sugar cane if there's another sugar cane above it
The server i play have jobs, and the farmer one if you break a 3 tall sugar cane from the bottom only counts as one, so with this option you have to break from top to bottom, so it counts as 3 blocks

**Comment by DasHomi** [comment]
I think I'll implement an option to disable breaking the lowest block of sugar cane and bamboo, but making it so that one can only break bamboo from top to bottom isn't an option most people need, but I can add that as a module option (like enhanced suspicious block breaking).
