### ISSUE TITLE
Prevent breaking regular chests if they're non-empty

### ISSUE THREAD

**Issue by 0xallie** [DasHomi/preventer#26]
I keep accidentally breaking my chests with my Efficiency V golden axe. It's especially annoying on Hypixel where dropped items despawn within like a minute.

If it's possible to check if the chest is non-empty, then just use that I guess, otherwise maybe prevent breaking entirely, or only allow with non-golden/non-efficiency-enchanted tool or hand.

**Comment by DasHomi** [comment]
The idea sounds good, but I think it's not possible to detect if a chest is empty with a client-side mod. I'll take a look, and if it's not possible, I think I'll disable chest breaking entirely.
