### ISSUE TITLE
Suspicious Sand/Gravel module not showing up.

### ISSUE THREAD

**Issue by Papa3984** [DasHomi/preventer#27]
The prevent suspicion sand or gravel module is not showing up when I run Preventer.  I checked and I have the latest version running.  Not sure if I'm doing something wrong or it's just not there.

**Comment by DasHomi** [comment]
which minecraft and Preventer version are you using?

**Comment by Butterkeks1000** [comment]
Suspicious blocks do not exist in Minecraft version 1.19.4. 
They were added in version 1.20, which can be seen [here](https://minecraft.fandom.com/wiki/Suspicious_Block#History)

**Comment by DasHomi** [comment]
Yes, in the 1.19.4-1.0 preventer version, I didn't add that option, as the block does not exist there. That should be the reason you can't find it.

**Comment by Papa3984** [comment]
Makes perfect sense.  So sorry.  Thanks, great mod.
