### ISSUE TITLE
The override button doesn't work properly 

### ISSUE THREAD

**Issue by katipatataki** [DasHomi/preventer#28]
I wanted to strip some logs for a floor that I wanted to made but when I pressed the override button I couldnt strip them. Then I started spamming the button and only then it let me strip some logs and that wasnt consistent. I use the latest version (1.20.X-1.0) and I dont think I did something wrong

Now if it is a bug I want to suggest how the the button should work. when you press the button it should allow you to do any action for some time (5-10 seconds) and every time an action that you prevent happens it will restart the timer. Btw I dont know if this is how it works. I cant test it

**Comment by DasHomi** [comment]
You have to hold the button, the override is only active while the button is pressed (the text will still be there a few seconds after the button has been released, but that will be fixed in preventer 1.1)

**Comment by katipatataki** [comment]
ok thanks. But if this is the case update the description of the mod to say "hold" instead of ''press''

**Comment by DasHomi** [comment]
yeah i'll do that
