### ISSUE TITLE
Prevent giving mobs renamed items

### ISSUE THREAD

**Issue by KiiwiTrio** [DasHomi/preventer#33]
Prevent renamed or offhanded items from being used in these scenarios:
-Breeding or feeding mobs
-Taming mobs
-Giving items to Allays
-Giving gold to Piglins
-Using golden apples on Zombie Villagers
-Repairing Iron Golems

Mainly suggesting this because I wouldn't want mobs to consume my valuable custom items on a certain server I play on.

**Comment by DasHomi** [comment]
Sounds good. I think I'll add it as a general "prevent renamed item use/interact"
