### ISSUE TITLE
2 suggestions/bugs

### ISSUE THREAD

**Issue by katipatataki** [DasHomi/preventer#36]
1) when you have "prevent renamed block placement" you cant place renamed shulker boxes making them unusable
2) when you have "prevent tool dropping" LOTS of items are not in this category (like Tridents, Totems of undying, Fishing rods, armor pieces, Bows, elytra, and many more) which are more important than a wooden pickaxe

**Comment by DasHomi** [comment]
The second one sounds good, but maby i'll change it to "important items" or something like that. But for the first one, could you clarify what exactly the problem is, because isn't the entire point of shulker boxes to place them?

**Comment by katipatataki** [comment]
First I am probably the only person who complains about this because I use both common and renamed shulker boxes at the same time (and I need that prevention for other rare blocks). For me It is really frustrating wanting to take 1 item out of a shulker box, you place it and you see that it is a renamed one so you have to press the override button to place it. And when this happens lots of times in an hour it is really annoying. Also unlike other blocks when you place them they dont lose their name tags so they can still keep "their specials name". Besides that the reason why I wrote in the title "2 suggestion/bugs" was due to those 2 things are really minor and only frustrate me. So if you dont change them they wont probably effect anyone else. I hope this helped you to understand what am I saying.

**Comment by DasHomi** [comment]
I'll change both. I just misread your question, but now I understand it, and it sounds perfectly reasonable.
