### ISSUE TITLE
Change the hotkey from "r" to make it editable

### ISSUE THREAD

**Issue by the-biggest-birfd** [DasHomi/preventer#37]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I want to spirnt because my sprint is R

**Describe the solution you'd like**

title

**Comment by the-biggest-birfd** [comment]
when i change it, it does not effect the game

**Comment by DasHomi** [comment]
which preventer and minecraft version are you using?

**Comment by the-biggest-birfd** [comment]
sorry it was another mod that was preventing keybinds from working, thanks for you time
