### ISSUE TITLE
Prevent Offhand Placing

### ISSUE THREAD

**Issue by theelevinr** [DasHomi/preventer#38]
**Prevent placing blocks from the offhand.**

When carrying a light source using shaders or a dynamic lights mod, you often never want to place the item in your offhand.
This is hard to prevent when eating or performing other right-click actions.

A configurable whitelist/blacklist to determine which blocks to block would also be brilliant. This way placing regular blocks would still be possible in the case described above.

**Comment by DasHomi** [comment]
Disabling offhand placement sounds like a good idea, and I'll do it. Adding blacklists and whitelists is an idea I've had in mind for a long time, but I think it could be a bit complex to have blacklists and the regular preventer options in one mod, so I decided I'd rather put that in another mod. But as a configuration for something like offhand placement, I may add black/white lists if I find a good way to do so. Otherways, I'll just add a disabled offhand placement for light sources/torches.
