### ISSUE TITLE
[Suggestion] Remove spiders from neutral mob attack prevention

### ISSUE THREAD

**Issue by BlueJayofEvil** [DasHomi/preventer#39]
I'd like to request the neutral mob attack prevention remove spiders from its coverage.
While spiders may technically be neutral mobs in the game, they are hostile unless in daylight. It's annoying to be fending off zombies, creepers, skeletons, etc. and have a spider attacking you and need the override key held to attack them in frantic situations.
Other than that, the neutral mob attack prevention has been working quite well.
Thank you for your time.

**Comment by DasHomi** [comment]
Yeah, it would be better to detect if mobs are Argo at you, but it's probably very hard to implement, so just removing them should be enough. So I'll do that.

**Comment by BlueJayofEvil** [comment]
I just realized Endermen are also covered by that. Might want to remove them from that too. Had to fend off one who was aggro and the prevention text graced my screen,
