### ISSUE TITLE
Prevent firework rocket use option no longer works

### ISSUE THREAD

**Issue by Jim3535** [DasHomi/preventer#44]
This option used to work, but now the game lets you launch rockets up into the air if you are standing on the ground.

Steps to reproduce:
1. Turn prevent firework rocket on
2. Select rockets in your hotbar
3. Point the crosshair at the ground near you and right click

Environment:
* java 17
* minecraft 1.20.1
* fabricloader 0.14.22
* fabric-api 0.90.7+1.20.1
* preventer 1.0.0

[latest.log](https://github.com/DasHomi/preventer/files/13340958/latest.log)

![2023-11-13_12 25 18](https://github.com/DasHomi/preventer/assets/120746893/a1020f64-a685-4d0a-9ef8-a5a4968acb83)

**Comment by DasHomi** [comment]
Maybe I misunderstand the issue, but I have not been able to reproduce it. In my tests, with the option enabled, i can't launch rockets. Are you sure you have enabled the "Prevent firework rocket use" for the hand in which you are using the rockets? What blocks are you targeting while the rockets are still being launched?

**Comment by Jim3535** [comment]
I was confused about your question about which hand would be prevented from using rockets. I dug through the menus and managed to find the setting. It turns out it works if I turn off firework use for the main hand (and I left the off hand "prevented" too).

What's odd is that it used to work, and I didn't change any config settings, so I don't know how it stopped working unless the setting is new. In either case, it might not be the best UI to split the options to separate tabs without a note or indicator.

**Comment by DasHomi** [comment]
Yes, you are right. I'll add a note to the option that it can be configured further under the config tab until I find a way to add dropdowns (which would be my preferred place to add the options). Do you know which preventer version you used when it was still working?

**Comment by Jim3535** [comment]
I'm not sure. I tried testing the beta version for 1.20 since it's the only other one listed on modrinth. It still works like the newer version.

I'm going to close this out as a combination of user error and UI that's not clear. There's aways a chance that I just never triggered rockets on the ground while in the main hand. It doesn't seem worth chasing that thread.
