### ISSUE TITLE
[Feature Request] Carpet breaking prevention

### ISSUE THREAD

**Issue by BlueJayofEvil** [DasHomi/preventer#46]
I'd like to suggest adding carpet breaking prevention as an option.
Carpet breaks so dang easily and accidentally destroying the carpeted flooring of something important (e.g. enderman farms with hoppers to destroy collected drops covered by carpet for aesthetics) is an issue that this could help with.
Moss carpet should probably also be covered by this (for those who do crazy things like bridge over lava with it for traps or insane nether challenges).

Thank you!

**Comment by DasHomi** [comment]
Sounds like a good idea, i'll add that.
