### ISSUE TITLE
Prevent signs placed on chests from being modified

### ISSUE THREAD

**Issue by 7coil** [DasHomi/preventer#51]
**Is your feature request related to a problem? Please describe.**
**As a** user  
**When** I accidentally right click a sign that is attached to a chest
**Then** I should be prevented from editing the sign

Alternatively, there could also be a module for preventing sign editing in general, with the chest thing as a module config

**Describe the solution you'd like**

```py
# N.B. logic slightly more advanced than pseudocode
if (block InstanceOf WallSign) and (blockBehind InstanceOf Chest):
  log("prevented sign editing")
  return FAIL
```

**Comment by DasHomi** [comment]
Sounds like a good idea, i think i'll do it as a "prevent sign editing" module with a config option that changes it to "prevent chest sign editing".

**Comment by Butterkeks1000** [comment]
🤓

**Comment by Butterkeks1000** [comment]
🤓
