### ISSUE TITLE
Allow override key to switch between "hold" and "toggle"

### ISSUE THREAD

**Issue by BlueJayofEvil** [DasHomi/preventer#70]
**Is your feature request related to a problem? Please describe.**
Sometimes holding the override key can be burdensome depending on the circumstance (e.g. trying to slay angrily zombie piglins swarming you.) In such circumstances it would be beneficial to be able to "toggle" the override on until any troublesome situation is dealt with, then it could be turned off again.

**Describe the solution you'd like**
An option to switch modes for the override key between "hold" and "toggle"
Alternately, a separate keybind for an override toggle.

Again, thank you for this great mod. 😎

**Comment by DasHomi** [comment]
Thanks for your ideas, I'll look at implementing them when I have more time.

**Comment by DasHomi** [comment]
Mostly implemented in #61 as one can just toggle off the entire mod temporarily.
