### ISSUE TITLE
Prevent breaking obsidian while holding end crystals (this is helpful actually)

### ISSUE THREAD

**Issue by janga123** [DasHomi/preventer#81]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by DasHomi** [comment]
I don't really understand how one would accidentally break an obsidian block while holding an end crystal in the hand/offhand. Could you please elaborate on what the problem is?

**Comment by janga123** [comment]
It will basically prevent the tick where it starts breaking. It makes it so placing crystals is more responsive. The main problem is that you cant place a crystal when spamming left and right click because of this. if you want more info you can dm me my discord is "jangabanga"

Thanks

**Comment by janga123** [comment]
or even a module that prevents breaking obsidian. there is still the override key but while holding an end crystal would be helpful too

**Comment by DasHomi** [comment]
Well, preventer isn't really supposed to be a PVP mod, so I won't implement this.

**Comment by janga123** [comment]
yo did you check your discord?
